export const DASHBOARD_ACCESS = Object.freeze({
  CLIENTES: 'CLIENTES',
  PEDIDOS: 'PEDIDOS',
  UBICACIONES: 'UBICACIONES',
  PREPARACION: 'PREPARACION',
  CARGA: 'CARGA',
  JORNADAS: 'JORNADAS',
  DESPACHOS: 'DESPACHOS',
  CAMIONES: 'CAMIONES',
  CHOFERES: 'CHOFERES',
  RUTAS: 'RUTAS',
  PRODUCTOS: 'PRODUCTOS',
  CATEGORIAS: 'CATEGORIAS',
  USUARIOS: 'USUARIOS',
  MI_JORNADA: 'MI_JORNADA',
});

export const DASHBOARD_LEVELS = Object.freeze({
  INFO: 'INFO',
  SUCCESS: 'SUCCESS',
  WARNING: 'WARNING',
  DANGER: 'DANGER',
});

export const DASHBOARD_NOTIFICATION_TYPES = Object.freeze({
  PEDIDO_ESTADO: 'PEDIDO_ESTADO',
  PEDIDO_LISTO: 'PEDIDO_LISTO',
  PEDIDO_PREPARACION: 'PEDIDO_PREPARACION',
  CARGA_PENDIENTE: 'CARGA_PENDIENTE',
  CARGA_CONFIRMADA: 'CARGA_CONFIRMADA',
  JORNADA_ASIGNADA: 'JORNADA_ASIGNADA',
  JORNADA_SIN_CHOFER: 'JORNADA_SIN_CHOFER',
  DESPACHO_NO_ENTREGADO: 'DESPACHO_NO_ENTREGADO',
  STOCK_BAJO: 'STOCK_BAJO',
  ORDEN_COMPRA_PENDIENTE: 'ORDEN_COMPRA_PENDIENTE',
});
