export const ROLES = {
  ADMIN: 'ADMIN',
  COMPRAS: 'COMPRAS',
  BODEGA: 'BODEGA',
  VENTAS: 'VENTAS',
  LOGISTICA: 'LOGISTICA',
  CHOFER: 'CHOFER',
};

export const PERMISSIONS = {
  USUARIOS_GESTIONAR: 'USUARIOS_GESTIONAR',

  CLIENTES_LEER: 'CLIENTES_LEER',
  CLIENTES_GESTIONAR: 'CLIENTES_GESTIONAR',

  CATALOGO_LEER: 'CATALOGO_LEER',
  CATALOGO_GESTIONAR: 'CATALOGO_GESTIONAR',

  UBICACIONES_LEER: 'UBICACIONES_LEER',
  UBICACIONES_GESTIONAR: 'UBICACIONES_GESTIONAR',

  RUTAS_LEER: 'RUTAS_LEER',
  RUTAS_GESTIONAR: 'RUTAS_GESTIONAR',

  PEDIDOS_LEER: 'PEDIDOS_LEER',
  PEDIDOS_CREAR: 'PEDIDOS_CREAR',
  PEDIDOS_EDITAR: 'PEDIDOS_EDITAR',
  PEDIDOS_CANCELAR: 'PEDIDOS_CANCELAR',
  PEDIDOS_ENVIAR_PREPARACION: 'PEDIDOS_ENVIAR_PREPARACION',
  PEDIDOS_PREPARAR: 'PEDIDOS_PREPARAR',
  PEDIDOS_FINALIZAR_PREPARACION: 'PEDIDOS_FINALIZAR_PREPARACION',

  CARGAS_LEER: 'CARGAS_LEER',
  CARGAS_ACTUALIZAR: 'CARGAS_ACTUALIZAR',
  CARGAS_CONFIRMAR: 'CARGAS_CONFIRMAR',

  CAMIONES_LEER: 'CAMIONES_LEER',
  CAMIONES_GESTIONAR: 'CAMIONES_GESTIONAR',

  CHOFERES_LEER: 'CHOFERES_LEER',
  CHOFERES_GESTIONAR: 'CHOFERES_GESTIONAR',

  JORNADAS_LEER: 'JORNADAS_LEER',
  JORNADAS_GENERAR: 'JORNADAS_GENERAR',
  JORNADAS_RECALCULAR: 'JORNADAS_RECALCULAR',
  JORNADAS_ASIGNAR_CHOFER: 'JORNADAS_ASIGNAR_CHOFER',
  JORNADAS_INICIAR: 'JORNADAS_INICIAR',
  JORNADAS_FINALIZAR: 'JORNADAS_FINALIZAR',

  DESPACHOS_LEER: 'DESPACHOS_LEER',
  DESPACHOS_ENTREGAR: 'DESPACHOS_ENTREGAR',
  DESPACHOS_NO_ENTREGAR: 'DESPACHOS_NO_ENTREGAR',
  DESPACHOS_CANCELAR: 'DESPACHOS_CANCELAR',
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: ['*'],

  [ROLES.VENTAS]: [
    PERMISSIONS.CLIENTES_LEER,
    PERMISSIONS.CLIENTES_GESTIONAR,
    PERMISSIONS.CATALOGO_LEER,
    PERMISSIONS.UBICACIONES_LEER,
    PERMISSIONS.UBICACIONES_GESTIONAR,
    PERMISSIONS.PEDIDOS_LEER,
    PERMISSIONS.PEDIDOS_CREAR,
    PERMISSIONS.PEDIDOS_EDITAR,
    PERMISSIONS.PEDIDOS_CANCELAR,
    PERMISSIONS.PEDIDOS_ENVIAR_PREPARACION,
  ],

  [ROLES.BODEGA]: [
    PERMISSIONS.CLIENTES_LEER,
    PERMISSIONS.CATALOGO_LEER,
    PERMISSIONS.PEDIDOS_LEER,
    PERMISSIONS.PEDIDOS_PREPARAR,
    PERMISSIONS.PEDIDOS_FINALIZAR_PREPARACION,
    PERMISSIONS.CARGAS_LEER,
    PERMISSIONS.CARGAS_ACTUALIZAR,
    PERMISSIONS.CARGAS_CONFIRMAR,
    PERMISSIONS.CAMIONES_LEER,
  ],

  [ROLES.LOGISTICA]: [
    PERMISSIONS.CLIENTES_LEER,
    PERMISSIONS.CATALOGO_LEER,
    PERMISSIONS.UBICACIONES_LEER,
    PERMISSIONS.RUTAS_LEER,
    PERMISSIONS.RUTAS_GESTIONAR,
    PERMISSIONS.PEDIDOS_LEER,
    PERMISSIONS.CAMIONES_LEER,
    PERMISSIONS.CAMIONES_GESTIONAR,
    PERMISSIONS.CHOFERES_LEER,
    PERMISSIONS.JORNADAS_LEER,
    PERMISSIONS.JORNADAS_GENERAR,
    PERMISSIONS.JORNADAS_RECALCULAR,
    PERMISSIONS.JORNADAS_ASIGNAR_CHOFER,
    PERMISSIONS.DESPACHOS_LEER,
    PERMISSIONS.DESPACHOS_CANCELAR,
  ],

  [ROLES.CHOFER]: [
    PERMISSIONS.CHOFERES_LEER,
    PERMISSIONS.JORNADAS_LEER,
    PERMISSIONS.JORNADAS_INICIAR,
    PERMISSIONS.JORNADAS_FINALIZAR,
    PERMISSIONS.DESPACHOS_LEER,
    PERMISSIONS.DESPACHOS_ENTREGAR,
    PERMISSIONS.DESPACHOS_NO_ENTREGAR,
  ],

  [ROLES.COMPRAS]: [
    PERMISSIONS.CATALOGO_LEER,
    PERMISSIONS.CATALOGO_GESTIONAR,
  ],
};

export const getPermissionsForRole = (role) => {
  const permissions = ROLE_PERMISSIONS[role] ?? [];

  if (permissions.includes('*')) {
    return Object.values(PERMISSIONS);
  }

  return permissions;
};

export const hasPermission = (
  role,
  permission,
) => {
  const permissions = ROLE_PERMISSIONS[role] ?? [];

  return (
    permissions.includes('*') ||
    permissions.includes(permission)
  );
};

export const isAdmin = (user) =>
  !user || user?.rol === ROLES.ADMIN;
