export const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  COMPRAS: 'COMPRAS',
  BODEGA: 'BODEGA',
  VENTAS: 'VENTAS',
  LOGISTICA: 'LOGISTICA',
  CHOFER: 'CHOFER',
});

export const PERMISSIONS = Object.freeze({
  USUARIOS_GESTIONAR: 'USUARIOS_GESTIONAR',

  CLIENTES_LEER: 'CLIENTES_LEER',
  CLIENTES_GESTIONAR: 'CLIENTES_GESTIONAR',

  CATALOGO_LEER: 'CATALOGO_LEER',
  CATALOGO_GESTIONAR: 'CATALOGO_GESTIONAR',

  UBICACIONES_LEER: 'UBICACIONES_LEER',
  UBICACIONES_GESTIONAR: 'UBICACIONES_GESTIONAR',

  RUTAS_LEER: 'RUTAS_LEER',
  RUTAS_GESTIONAR: 'RUTAS_GESTIONAR',

  PEDIDOS_LEER: 'PEDIDOS_LEER',
  PEDIDOS_CREAR: 'PEDIDOS_CREAR',
  PEDIDOS_EDITAR: 'PEDIDOS_EDITAR',
  PEDIDOS_CANCELAR: 'PEDIDOS_CANCELAR',
  PEDIDOS_ENVIAR_PREPARACION: 'PEDIDOS_ENVIAR_PREPARACION',
  PEDIDOS_PREPARAR: 'PEDIDOS_PREPARAR',
  PEDIDOS_FINALIZAR_PREPARACION: 'PEDIDOS_FINALIZAR_PREPARACION',

  CARGAS_LEER: 'CARGAS_LEER',
  CARGAS_ACTUALIZAR: 'CARGAS_ACTUALIZAR',
  CARGAS_CONFIRMAR: 'CARGAS_CONFIRMAR',

  CAMIONES_LEER: 'CAMIONES_LEER',
  CAMIONES_GESTIONAR: 'CAMIONES_GESTIONAR',

  CHOFERES_LEER: 'CHOFERES_LEER',
  CHOFERES_GESTIONAR: 'CHOFERES_GESTIONAR',
  CHOFER_PERFIL_PROPIO_LEER: 'CHOFER_PERFIL_PROPIO_LEER',

  JORNADAS_LEER: 'JORNADAS_LEER',
  JORNADAS_MAPA_GENERAL: 'JORNADAS_MAPA_GENERAL',
  JORNADAS_GENERAR: 'JORNADAS_GENERAR',
  JORNADAS_RECALCULAR: 'JORNADAS_RECALCULAR',
  JORNADAS_ASIGNAR_CHOFER: 'JORNADAS_ASIGNAR_CHOFER',
  JORNADAS_INICIAR: 'JORNADAS_INICIAR',
  JORNADAS_FINALIZAR: 'JORNADAS_FINALIZAR',

  DESPACHOS_LEER: 'DESPACHOS_LEER',
  DESPACHOS_ENTREGAR: 'DESPACHOS_ENTREGAR',
  DESPACHOS_NO_ENTREGAR: 'DESPACHOS_NO_ENTREGAR',
  DESPACHOS_CANCELAR: 'DESPACHOS_CANCELAR',
});

export const ROLE_LABELS = Object.freeze({
  [ROLES.ADMIN]: 'Administrador',
  [ROLES.COMPRAS]: 'Compras',
  [ROLES.BODEGA]: 'Bodega',
  [ROLES.VENTAS]: 'Ventas',
  [ROLES.LOGISTICA]: 'Logística',
  [ROLES.CHOFER]: 'Chofer',
});
